import { AppData, DebtType, FixedExpense } from './types';

export const CATEGORIAS = [
  'comida',
  'transporte',
  'vivienda',
  'salud',
  'entretenimiento',
  'servicios',
  'salario',
  'deuda',
  'otros',
] as const;

export type CategoryName = (typeof CATEGORIAS)[number];

export const CATEGORIA_COLOR: Record<string, string> = {
  comida: '#F4C95D',
  transporte: '#4D9DE0',
  vivienda: '#B08BEF',
  salud: '#F0525D',
  entretenimiento: '#35D0BA',
  servicios: '#6FCF97',
  salario: '#2BC77B',
  deuda: '#F2994A',
  otros: '#9AA3AD',
};

export const DEUDA_TIPOS: DebtType[] = ['tarjeta', 'prestamo', 'prestado'];

export const TEXTOS = {
  es: {
    app_title: 'Pock',
    nav_inicio: 'Inicio',
    nav_historial: 'Historial',
    nav_deudas: 'Deudas',
    nav_ahorros: 'Ahorros',
    nav_resumen: 'Corte / Mes',
    nav_ajustes: 'Ajustes',
    dinero_libre: 'DINERO LIBRE ACTUAL',
    saldo_base: 'Saldo base',
    saldo_disponible: 'Saldo disponible',
    alerta_bajo: 'Alerta de saldo bajo',
    deficit: 'Déficit de',
    registrar_mov: 'Registrar movimiento',
    desc: 'Descripción',
    monto: 'Monto (en colones)',
    categoria_lbl: 'Categoría',
    cat_comida: '🍔 Comida',
    cat_transporte: '🚌 Transporte',
    cat_vivienda: '🏠 Vivienda',
    cat_salud: '💊 Salud',
    cat_entretenimiento: '🎮 Entretenimiento',
    cat_servicios: '🧾 Servicios',
    cat_salario: '💼 Salario',
    cat_otros: '🔹 Otros',
    cat_deuda: '💸 Deuda',
    grafico_titulo: 'Gastos por categoría',
    grafico_vacio: 'Aún no hay gastos para graficar.',
    gasto_btn: 'Gasto',
    ingreso_btn: 'Ingreso',
    enter_hint: '⏎ Enter registra Gasto · ⇧Enter registra Ingreso',
    gastado_hoy: 'Gastado hoy',
    ingresado_hoy: 'Ingresado hoy',
    ultimos_movimientos: 'Últimos movimientos',
    ver_todo_historial: 'Ver todo el historial',
    categorias_frecuentes: 'Acceso rápido',
    sin_mov_recientes: 'No hay movimientos registrados hoy.',
    
    // Presupuestos por categoría
    btn_presupuestos: 'Presupuestos',
    tit_presupuestos: 'Límites de Presupuesto por Categoría',
    desc_presupuestos: 'Define un tope mensual opcional por categoría para controlar tus gastos.',
    tope_actual: 'Tope mensual',
    sin_tope: 'Sin límite',
    cerca_limite: '⚠️ Cerca del límite',
    excedido_limite: '🚨 Excedido por',
    guardar_topes: 'Guardar presupuestos',
    
    // Historial
    historial_titulo: 'Historial de Movimientos',
    filtro_todos: 'Todos',
    filtro_gastos: 'Gastos',
    filtro_ingresos: 'Ingresos',
    buscar_placeholder: 'Buscar por descripción, categoría o monto...',
    filtro_cat_todas: 'Todas las categorías',
    sin_mov_filtro: 'No hay movimientos con los filtros aplicados.',
    sin_mov: 'No hay movimientos registrados todavía.',
    editar_mov: 'Editar movimiento',
    guardar_cambios: 'Guardar cambios',
    exportar_csv: 'Exportar a CSV / Excel',
    eliminar_confirm: '¿Deseas eliminar este movimiento del historial?',
    
    // Corte / Mes y Métricas
    resumen_titulo: 'Corte y Ciclo de Mes',
    metricas_ciclo_tit: 'Métricas del Ciclo Actual',
    metricas_ingresos: 'Ingresos del mes',
    metricas_gastos: 'Gastos del mes',
    metricas_ahorro: 'Excedente / Ahorro neto',
    metricas_tasa_ahorro: 'Tasa de ahorro',
    metricas_mayor_gasto: 'Mayor categoría de gasto',
    resumen_card_tit: 'Reiniciar cuentas para un nuevo mes',
    resumen_card_sub: 'Esto cerrará el ciclo actual, guardará un resumen de balance y configurará tu nuevo saldo base.',
    resumen_btn: 'Hacer Corte de Mes',
    resumen_ingreso_lbl: 'Nuevo saldo base inicial (₡):',
    resumen_btn_ejecutar: 'Confirmar Corte',
    resumen_cancelar: 'Cancelar',
    historial_cortes_tit: 'Historial de Cortes Pasados',
    sin_cortes_previos: 'Aún no has realizado cierres de mes.',
    
    // Gastos fijos / Plantillas
    gastos_fijos_tit: 'Gastos Fijos Recurrentes',
    gastos_fijos_sub: 'Plantillas de gastos mensuales (alquiler, suscripciones, servicios) listos para aplicar con un clic.',
    btn_aplicar_fijos: 'Aplicar gastos fijos al nuevo mes',
    agregar_fijo: 'Agregar gasto recurrente',
    fijo_activo: 'Activo para el corte',
    fijos_aplicados_exito: 'Gastos fijos aplicados correctamente al historial.',
    
    // Ajustes
    ajustes_titulo: 'Ajustes de la App',
    ajustes_tema_tit: 'Tema de la aplicación',
    ajustes_tema_desc: 'Elige la apariencia visual que mejor se adapte a tu entorno y comodidad visual.',
    tema_oscuro: 'Oscuro',
    tema_claro: 'Claro',
    tema_sistema: 'Sistema',
    ajustes_alerta_tit: 'Alerta de saldo bajo',
    ajustes_btn_guardar: 'Guardar límite',
    ajustes_idioma_tit: 'Idioma de la aplicación',
    ajustes_datos_tit: 'Gestión de Datos',
    ajustes_exportar: 'Exportar Backup (JSON)',
    ajustes_importar: 'Importar Backup (JSON)',
    ajustes_reiniciar: 'Restablecer datos predeterminados',
    aviso_desc: 'Escribe una descripción.',
    aviso_monto: 'Ingresa un monto válido mayor a 0.',
    corte_msj: '¿Estás seguro de que deseas cerrar las cuentas del ciclo actual y comenzar un nuevo mes? Esto archivará las métricas y reiniciará el saldo base.',
    limite_guardado: 'Guardado exitosamente',
    limite_error: 'Ingresa un número válido.',
    corte_exito: 'Ciclo reiniciado correctamente',
    corte_error: 'Ingresa un número válido para el saldo base.',
    
    // Deudas
    deudas_titulo: 'Gestión de Deudas',
    deuda_registrar_tit: 'Registrar nueva deuda',
    deuda_tipo_lbl: 'Tipo de deuda',
    deuda_tipo_tarjeta: 'Tarjeta de crédito',
    deuda_tipo_prestamo: 'Préstamo personal',
    deuda_tipo_prestado: 'Dinero prestado',
    deuda_acreedor: 'Acreedor',
    deuda_monto_total: 'Monto total',
    deuda_monto_pagado: 'Monto pagado / Cuota inicial',
    deuda_fecha_limite: 'Fecha límite (opcional)',
    deuda_btn_guardar: 'Guardar deuda',
    deuda_lista_tit: 'Deudas activas',
    deuda_sin_deudas: 'No tienes deudas registradas.',
    deuda_btn_abonar: 'Abonar a deuda',
    deuda_pagada: 'Pagada por completo',
    deuda_prompt_abono_tit: 'Abonar a deuda',
    deuda_prompt_abono: '¿Cuánto quieres abonar? (₡)',
    deuda_abono_btn: 'Confirmar abono',
    deuda_cancelar: 'Cancelar',
    aviso_deuda_acreedor: 'Escribe el nombre del acreedor.',
    aviso_deuda_monto: 'Ingresa un monto total válido mayor a 0.',
    deuda_guardada: 'Deuda guardada correctamente',
    eliminar: 'Eliminar',
    editar: 'Editar',
    
    // Ahorros / Metas
    ahorros_titulo: 'Metas de Ahorro',
    ahorro_nueva_meta: 'Crear nueva meta',
    ahorro_nombre: 'Nombre de la meta',
    ahorro_meta: 'Monto objetivo (₡)',
    ahorro_ahorrado: 'Monto inicial ahorrado (₡)',
    ahorro_fecha_limite: 'Fecha límite (opcional)',
    ahorro_btn_guardar: 'Guardar meta',
    ahorro_lista_tit: 'Tus metas activas',
    ahorro_sin_metas: 'No tienes metas de ahorro registradas.',
    ahorro_btn_abonar: 'Abonar ahorro',
    ahorro_btn_retirar: 'Retirar ahorro',
    ahorro_completada: '¡Meta alcanzada!',
    ahorro_descontar_libre: 'Descontar del saldo libre actual',
    ahorro_total_ahorrado: 'Total acumulado en metas',
    ahorro_prompt_abono_tit: 'Abonar a meta de ahorro',
    ahorro_prompt_abono: '¿Cuánto deseas abonar? (₡)',
    ahorro_abono_btn: 'Confirmar abono',
    ahorro_prompt_retiro_tit: 'Retirar fondos de la meta',
    ahorro_prompt_retiro: '¿Cuánto deseas retirar? (₡)',
    ahorro_retiro_btn: 'Confirmar retiro',
    ahorro_guardada: 'Meta guardada correctamente',
    
    // Categorías y atajos
    cat_personalizada_tit: 'Personalización Total de Categorías',
    cat_personalizadas_desc: 'Gestiona todas las categorías de Pock. Puedes eliminar cualquier categoría existente que no utilices, crear nuevas categorías personalizadas o restaurar las predeterminadas en cualquier momento.',
    cat_activas: 'Categorías Activas',
    cat_ocultas: 'Categorías Predeterminadas Eliminadas',
    cat_restaurar: 'Restaurar',
    cat_restaurar_todas: 'Restablecer todas las predeterminadas',
    cat_eliminar_btn: 'Eliminar',
    cat_no_hay_activas: 'No hay categorías activas. Crea una nueva o restaura las predeterminadas.',
    cat_agregar_btn: 'Nueva categoría',
    cat_nombre_placeholder: 'Ej. Mascotas, Gimnasio, Freelance...',
    cat_crear_btn: 'Crear Categoría',
    cat_eliminar: 'Eliminar categoría',
    cat_mostrar_todas: 'Desplegar categorías',
    cat_ocultar_lista: 'Plegar lista',
    categoria_existe: 'Esta categoría ya existe.',
    grafico_evolucion_tit: 'Evolución Diaria de Gastos',
    grafico_evolucion_sub: 'Gastos día a día registrados en el ciclo',
    grafico_evolucion_vacio: 'Aún no hay gastos registrados en este ciclo.',
    deshacer: 'Deshacer',
    movimiento_eliminado: 'Movimiento eliminado',
    deuda_eliminada: 'Deuda eliminada',
    meta_eliminada: 'Meta eliminada',
    atajo_hint: '⏎ Enter = Gasto · ⇧ Enter = Ingreso',
  },
  en: {
    app_title: 'Pock',
    nav_inicio: 'Home',
    nav_historial: 'History',
    nav_deudas: 'Debts',
    nav_ahorros: 'Savings',
    nav_resumen: 'Month Cut',
    nav_ajustes: 'Settings',
    dinero_libre: 'CURRENT FREE MONEY',
    saldo_base: 'Base balance',
    saldo_disponible: 'Available balance',
    alerta_bajo: 'Low balance alert',
    deficit: 'Deficit of',
    registrar_mov: 'Register transaction',
    desc: 'Description',
    monto: 'Amount (in colones)',
    categoria_lbl: 'Category',
    cat_comida: '🍔 Food',
    cat_transporte: '🚌 Transport',
    cat_vivienda: '🏠 Housing',
    cat_salud: '💊 Health',
    cat_entretenimiento: '🎮 Entertainment',
    cat_servicios: '🧾 Utilities',
    cat_salario: '💼 Salary',
    cat_otros: '🔹 Other',
    cat_deuda: '💸 Debt',
    grafico_titulo: 'Expenses by category',
    grafico_vacio: 'No expenses to chart yet.',
    gasto_btn: 'Expense',
    ingreso_btn: 'Income',
    enter_hint: '⏎ Enter logs Expense · ⇧Enter logs Income',
    gastado_hoy: 'Spent today',
    ingresado_hoy: 'Income today',
    ultimos_movimientos: 'Recent transactions',
    ver_todo_historial: 'View full history',
    categorias_frecuentes: 'Quick access',
    sin_mov_recientes: 'No transactions recorded today.',
    
    // Category budgets
    btn_presupuestos: 'Budgets',
    tit_presupuestos: 'Category Budget Caps',
    desc_presupuestos: 'Set an optional monthly cap per category to keep expenses under control.',
    tope_actual: 'Monthly cap',
    sin_tope: 'No limit',
    cerca_limite: '⚠️ Near budget limit',
    excedido_limite: '🚨 Exceeded by',
    guardar_topes: 'Save budgets',
    
    // History
    historial_titulo: 'Transaction History',
    filtro_todos: 'All',
    filtro_gastos: 'Expenses',
    filtro_ingresos: 'Incomes',
    buscar_placeholder: 'Search by description, category, or amount...',
    filtro_cat_todas: 'All categories',
    sin_mov_filtro: 'No transactions match the applied filters.',
    sin_mov: 'No transactions registered yet.',
    editar_mov: 'Edit transaction',
    guardar_cambios: 'Save changes',
    exportar_csv: 'Export to CSV / Excel',
    eliminar_confirm: 'Do you want to delete this transaction?',
    
    // Month cut & Metrics
    resumen_titulo: 'Month Cut & Cycle',
    metricas_ciclo_tit: 'Current Cycle Metrics',
    metricas_ingresos: 'Cycle Incomes',
    metricas_gastos: 'Cycle Expenses',
    metricas_ahorro: 'Surplus / Net Savings',
    metricas_tasa_ahorro: 'Savings Rate',
    metricas_mayor_gasto: 'Top Spending Category',
    resumen_card_tit: 'Reset accounts for a new month',
    resumen_card_sub: 'This will close the current cycle, save a balance summary, and set your new base balance.',
    resumen_btn: 'Perform Month Cut',
    resumen_ingreso_lbl: 'New initial base balance (₡):',
    resumen_btn_ejecutar: 'Confirm Cut',
    resumen_cancelar: 'Cancel',
    historial_cortes_tit: 'Past Monthly Closures',
    sin_cortes_previos: 'No previous monthly cuts yet.',
    
    // Fixed expenses
    gastos_fijos_tit: 'Recurring Fixed Expenses',
    gastos_fijos_sub: 'Monthly expense templates (rent, subscriptions, utilities) ready to apply in one click.',
    btn_aplicar_fijos: 'Apply fixed expenses to new month',
    agregar_fijo: 'Add recurring expense',
    fijo_activo: 'Active for cut',
    fijos_aplicados_exito: 'Fixed expenses successfully added to history.',
    
    // Settings
    ajustes_titulo: 'App Settings',
    ajustes_tema_tit: 'App Theme',
    ajustes_tema_desc: 'Choose the visual appearance that best fits your environment and eye comfort.',
    tema_oscuro: 'Dark',
    tema_claro: 'Light',
    tema_sistema: 'System',
    ajustes_alerta_tit: 'Low balance alert',
    ajustes_btn_guardar: 'Save limit',
    ajustes_idioma_tit: 'App Language',
    ajustes_datos_tit: 'Data Management',
    ajustes_exportar: 'Export Backup (JSON)',
    ajustes_importar: 'Import Backup (JSON)',
    ajustes_reiniciar: 'Reset default data',
    aviso_desc: 'Please enter a description.',
    aviso_monto: 'Please enter a valid amount greater than 0.',
    corte_msj: 'Are you sure you want to close current cycle accounts and start a new month? This will archive metrics and reset the base balance.',
    limite_guardado: 'Saved successfully',
    limite_error: 'Enter a valid number.',
    corte_exito: 'Cycle reset successfully',
    corte_error: 'Enter a valid number for the base balance.',
    
    // Debts
    deudas_titulo: 'Debt Management',
    deuda_registrar_tit: 'Register new debt',
    deuda_tipo_lbl: 'Debt type',
    deuda_tipo_tarjeta: 'Credit card',
    deuda_tipo_prestamo: 'Personal loan',
    deuda_tipo_prestado: 'Borrowed money',
    deuda_acreedor: 'Creditor',
    deuda_monto_total: 'Total amount',
    deuda_monto_pagado: 'Amount paid / Initial quota',
    deuda_fecha_limite: 'Due date (optional)',
    deuda_btn_guardar: 'Save debt',
    deuda_lista_tit: 'Active debts',
    deuda_sin_deudas: 'You have no debts registered.',
    deuda_btn_abonar: 'Make a payment',
    deuda_pagada: 'Fully paid off',
    deuda_prompt_abono_tit: 'Make a payment',
    deuda_prompt_abono: 'How much do you want to pay? (₡)',
    deuda_abono_btn: 'Confirm payment',
    deuda_cancelar: 'Cancel',
    aviso_deuda_acreedor: "Enter the creditor's name.",
    aviso_deuda_monto: 'Enter a valid total amount greater than 0.',
    deuda_guardada: 'Debt saved successfully',
    eliminar: 'Delete',
    editar: 'Edit',
    
    // Savings / Goals
    ahorros_titulo: 'Savings Goals',
    ahorro_nueva_meta: 'New savings goal',
    ahorro_nombre: 'Goal name',
    ahorro_meta: 'Target amount (₡)',
    ahorro_ahorrado: 'Initial saved amount (₡)',
    ahorro_fecha_limite: 'Target date (optional)',
    ahorro_btn_guardar: 'Save goal',
    ahorro_lista_tit: 'Your active goals',
    ahorro_sin_metas: 'No savings goals registered yet.',
    ahorro_btn_abonar: 'Deposit savings',
    ahorro_btn_retirar: 'Withdraw savings',
    ahorro_completada: 'Goal achieved!',
    ahorro_descontar_libre: 'Deduct from current free money',
    ahorro_total_ahorrado: 'Total accumulated in goals',
    ahorro_prompt_abono_tit: 'Deposit to savings goal',
    ahorro_prompt_abono: 'How much do you want to deposit? (₡)',
    ahorro_abono_btn: 'Confirm deposit',
    ahorro_prompt_retiro_tit: 'Withdraw from savings goal',
    ahorro_prompt_retiro: 'How much do you want to withdraw? (₡)',
    ahorro_retiro_btn: 'Confirm withdrawal',
    ahorro_guardada: 'Goal saved successfully',
    
    // Categories and shortcuts
    cat_personalizada_tit: 'Full Category Customization',
    cat_personalizadas_desc: 'Fully manage all app categories. Delete any existing category you do not use, create custom categories, or restore defaults at any time.',
    cat_activas: 'Active Categories',
    cat_ocultas: 'Deleted Default Categories',
    cat_restaurar: 'Restore',
    cat_restaurar_todas: 'Restore all default categories',
    cat_eliminar_btn: 'Delete',
    cat_no_hay_activas: 'No active categories. Create one or restore defaults.',
    cat_agregar_btn: 'New category',
    cat_nombre_placeholder: 'e.g. Pets, Gym, Freelance...',
    cat_crear_btn: 'Create Category',
    cat_eliminar: 'Delete category',
    cat_mostrar_todas: 'Expand categories',
    cat_ocultar_lista: 'Collapse list',
    categoria_existe: 'This category already exists.',
    grafico_evolucion_tit: 'Daily Spending Trend',
    grafico_evolucion_sub: 'Day by day expenses logged in this cycle',
    grafico_evolucion_vacio: 'No expenses recorded yet in this cycle.',
    deshacer: 'Undo',
    movimiento_eliminado: 'Movement deleted',
    deuda_eliminada: 'Debt deleted',
    meta_eliminada: 'Goal deleted',
    atajo_hint: '⏎ Enter = Expense · ⇧ Enter = Income',
  },
} as const;

export const DEFAULT_FIXED_EXPENSES: FixedExpense[] = [
  {
    id: 'fijo-alquiler',
    desc: 'Alquiler mensual',
    categoria: 'vivienda',
    monto: 60000.0,
    activo: true,
  },
  {
    id: 'fijo-internet',
    desc: 'Internet / WiFi',
    categoria: 'servicios',
    monto: 22000.0,
    activo: true,
  },
];

// Default initial data for fresh installations
export const INITIAL_DATA: AppData = {
  dinero_libre: 0.0,
  historial: [],
  limite_alerta: 0.0,
  idioma_actual: 'es',
  tema: 'dark',
  deudas: [],
  presupuestos_categoria: {},
  gastos_fijos: [],
  historial_cortes: [],
  metas_ahorro: [],
  categorias_personalizadas: [],
  categorias_ocultas: [],
};
